# permissions for end users to edit externalconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalconfigmap-editor-role
rules:
- apiGroups:
  - api.external-secrets-operator.app
  resources:
  - externalconfigmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.external-secrets-operator.app
  resources:
  - externalconfigmaps/status
  verbs:
  - get
