
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.external-secrets-operator.app
  resources:
  - externalbackends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.external-secrets-operator.app
  resources:
  - externalbackends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - api.external-secrets-operator.app
  resources:
  - externalconfigmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.external-secrets-operator.app
  resources:
  - externalconfigmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - api.external-secrets-operator.app
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.external-secrets-operator.app
  resources:
  - externalsecrets/status
  verbs:
  - get
  - patch
  - update
